###################################################
# This Compose file provides the development environment for the  app.
# 
###################################################

###################################################
# Services
#
# The services define the individual components of our application stack.
# For each service, a separate container will be launched.
###################################################
services:

  ###################################################
  # Service: client
  #
  # The client service is the React app that provides the frontend for the app.
  # When the container starts, it will use the image that results from building
  # the Dockerfile, targeting the dev stage.
  #
  # The Compose Watch configuration is used to automatically sync the code from
  # the host machine to the container. This allows the client to be automatically
  # reloaded when code changes are made.
  # 
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    ports:
      - 3001:3001
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /usr/local/app/frontend/src
        - path: ./frontend/package.json
          action: rebuild
